/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowb2 (void)
{
  GtkWidget *windowb2;
  GtkWidget *fixed2;
  GtkWidget *button1;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label1257;
  GtkWidget *buttonb3;
  GtkWidget *labelb4;

  windowb2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowb2), _("espace administrateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowb2), fixed2);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 216, 192);
  gtk_widget_set_size_request (button1, 184, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button1), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label1257 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label1257);
  gtk_box_pack_start (GTK_BOX (hbox3), label1257, FALSE, FALSE, 0);

  buttonb3 = gtk_button_new_with_mnemonic (_("Gestion des \303\251quipement agricoles"));
  gtk_widget_show (buttonb3);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonb3, 24, 96);
  gtk_widget_set_size_request (buttonb3, 500, 60);

  labelb4 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"brown\"> bienvenue dans votre espace administrateur</span>"));
  gtk_widget_show (labelb4);
  gtk_fixed_put (GTK_FIXED (fixed2), labelb4, 48, 16);
  gtk_widget_set_size_request (labelb4, 456, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelb4), TRUE);

  g_signal_connect ((gpointer) buttonb3, "clicked",
                    G_CALLBACK (on_buttonb3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowb2, windowb2, "windowb2");
  GLADE_HOOKUP_OBJECT (windowb2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowb2, button1, "button1");
  GLADE_HOOKUP_OBJECT (windowb2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowb2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowb2, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowb2, label1257, "label1257");
  GLADE_HOOKUP_OBJECT (windowb2, buttonb3, "buttonb3");
  GLADE_HOOKUP_OBJECT (windowb2, labelb4, "labelb4");

  return windowb2;
}

GtkWidget*
create_windowb3 (void)
{
  GtkWidget *windowb3;
  GtkWidget *fixed4;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *entryb3;
  GtkWidget *entryb4;
  GtkWidget *entryb5;
  GtkWidget *entryb6;
  GtkWidget *entry7;
  GtkWidget *entryb8;
  GtkWidget *labelb13;
  GtkWidget *labelb14;
  GtkWidget *labelb15;
  GtkWidget *labelb16;
  GtkWidget *labelb17;
  GtkWidget *labelb12;
  GtkWidget *buttonbackb2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label1256;
  GtkWidget *buttonb7;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label1255;
  GtkWidget *label100;
  GtkWidget *labelb8;
  GtkWidget *fixed6;
  GtkWidget *buttonb13;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label1260;
  GtkWidget *buttonbackb3;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label1261;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewb1;
  GtkWidget *labelb9;
  GtkWidget *fixed7;
  GtkWidget *entryb9;
  GtkWidget *buttonb9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label1263;
  GtkWidget *labelb25;
  GtkWidget *labelb24;
  GtkWidget *label1;
  GtkWidget *labelb10;
  GtkWidget *fixed8;
  GtkWidget *entryb10;
  GtkWidget *labelb29;
  GtkWidget *buttonb10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label1262;
  GtkWidget *labelb27;
  GtkWidget *labelb26;
  GtkWidget *labelb11;
  GtkWidget *fixed12;
  GtkWidget *combobox1;
  GtkWidget *recherche;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image17;
  GtkWidget *label1275;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview_rechercher;
  GtkWidget *label1274;

  windowb3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowb3), _("gestion d'\303\251quipements agricoles"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowb3), fixed4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook1, 8, 8);
  gtk_widget_set_size_request (notebook1, 632, 456);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entryb3 = gtk_entry_new ();
  gtk_widget_show (entryb3);
  gtk_fixed_put (GTK_FIXED (fixed5), entryb3, 216, 24);
  gtk_widget_set_size_request (entryb3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb3), 8226);

  entryb4 = gtk_entry_new ();
  gtk_widget_show (entryb4);
  gtk_fixed_put (GTK_FIXED (fixed5), entryb4, 216, 64);
  gtk_widget_set_size_request (entryb4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb4), 8226);

  entryb5 = gtk_entry_new ();
  gtk_widget_show (entryb5);
  gtk_fixed_put (GTK_FIXED (fixed5), entryb5, 216, 104);
  gtk_widget_set_size_request (entryb5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb5), 8226);

  entryb6 = gtk_entry_new ();
  gtk_widget_show (entryb6);
  gtk_fixed_put (GTK_FIXED (fixed5), entryb6, 216, 144);
  gtk_widget_set_size_request (entryb6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed5), entry7, 216, 184);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entryb8 = gtk_entry_new ();
  gtk_widget_show (entryb8);
  gtk_fixed_put (GTK_FIXED (fixed5), entryb8, 216, 224);
  gtk_widget_set_size_request (entryb8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb8), 8226);

  labelb13 = gtk_label_new_with_mnemonic (_("<span><b>Marque :</b></span>"));
  gtk_widget_show (labelb13);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb13, 8, 72);
  gtk_widget_set_size_request (labelb13, 168, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb13), TRUE);

  labelb14 = gtk_label_new_with_mnemonic (_("<span><b>Matricule:</b></span>"));
  gtk_widget_show (labelb14);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb14, 32, 112);
  gtk_widget_set_size_request (labelb14, 113, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb14), TRUE);

  labelb15 = gtk_label_new_with_mnemonic (_("<span><b>Num d'identifiant:</b></span>"));
  gtk_widget_show (labelb15);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb15, 0, 152);
  gtk_widget_set_size_request (labelb15, 184, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb15), TRUE);

  labelb16 = gtk_label_new_with_mnemonic (_("<span><b>Puissance:</b></span>"));
  gtk_widget_show (labelb16);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb16, 8, 192);
  gtk_widget_set_size_request (labelb16, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb16), TRUE);

  labelb17 = gtk_label_new_with_mnemonic (_("<span><b>Ann\303\251e :</b></span>"));
  gtk_widget_show (labelb17);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb17, 8, 232);
  gtk_widget_set_size_request (labelb17, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb17), TRUE);

  labelb12 = gtk_label_new_with_mnemonic (_("<span><b>Type :</b></span>"));
  gtk_widget_show (labelb12);
  gtk_fixed_put (GTK_FIXED (fixed5), labelb12, 24, 30);
  gtk_widget_set_size_request (labelb12, 125, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb12), TRUE);

  buttonbackb2 = gtk_button_new ();
  gtk_widget_show (buttonbackb2);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonbackb2, 40, 304);
  gtk_widget_set_size_request (buttonbackb2, 136, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonbackb2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label1256 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label1256);
  gtk_box_pack_start (GTK_BOX (hbox2), label1256, FALSE, FALSE, 0);

  buttonb7 = gtk_button_new ();
  gtk_widget_show (buttonb7);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonb7, 232, 288);
  gtk_widget_set_size_request (buttonb7, 130, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonb7), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label1255 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label1255);
  gtk_box_pack_start (GTK_BOX (hbox1), label1255, FALSE, FALSE, 0);

  label100 = gtk_label_new ("");
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed5), label100, 160, 264);
  gtk_widget_set_size_request (label100, 248, 16);

  labelb8 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"green\">ajouter</span>"));
  gtk_widget_show (labelb8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelb8);
  gtk_widget_set_size_request (labelb8, 116, -1);
  gtk_label_set_use_markup (GTK_LABEL (labelb8), TRUE);
  gtk_misc_set_alignment (GTK_MISC (labelb8), 0.41, 0.61);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  buttonb13 = gtk_button_new ();
  gtk_widget_show (buttonb13);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonb13, 40, 40);
  gtk_widget_set_size_request (buttonb13, 168, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonb13), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label1260 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label1260);
  gtk_box_pack_start (GTK_BOX (hbox6), label1260, FALSE, FALSE, 0);

  buttonbackb3 = gtk_button_new ();
  gtk_widget_show (buttonbackb3);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonbackb3, 288, 40);
  gtk_widget_set_size_request (buttonbackb3, 128, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonbackb3), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label1261 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label1261);
  gtk_box_pack_start (GTK_BOX (hbox7), label1261, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow1, 16, 128);
  gtk_widget_set_size_request (scrolledwindow1, 440, 192);

  treeviewb1 = gtk_tree_view_new ();
  gtk_widget_show (treeviewb1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewb1);
  gtk_widget_set_size_request (treeviewb1, 300, 200);

  labelb9 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"green\">afficher</span>"));
  gtk_widget_show (labelb9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelb9);
  gtk_widget_set_size_request (labelb9, 116, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelb9), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entryb9 = gtk_entry_new ();
  gtk_widget_show (entryb9);
  gtk_fixed_put (GTK_FIXED (fixed7), entryb9, 264, 128);
  gtk_widget_set_size_request (entryb9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb9), 8226);

  buttonb9 = gtk_button_new ();
  gtk_widget_show (buttonb9);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonb9, 208, 184);
  gtk_widget_set_size_request (buttonb9, 184, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonb9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label1263 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label1263);
  gtk_box_pack_start (GTK_BOX (hbox9), label1263, FALSE, FALSE, 0);

  labelb25 = gtk_label_new_with_mnemonic (_("<span><b>Matricule :</b></span>"));
  gtk_widget_show (labelb25);
  gtk_fixed_put (GTK_FIXED (fixed7), labelb25, 120, 136);
  gtk_widget_set_size_request (labelb25, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb25), TRUE);

  labelb24 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"blue\">veuillez introduire la matricule d'agricole a modifier</span>"));
  gtk_widget_show (labelb24);
  gtk_fixed_put (GTK_FIXED (fixed7), labelb24, 96, 40);
  gtk_widget_set_size_request (labelb24, 464, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelb24), TRUE);

  label1 = gtk_label_new ("");
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed7), label1, 288, 176);
  gtk_widget_set_size_request (label1, 416, 56);

  labelb10 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"green\">modifier</span>"));
  gtk_widget_show (labelb10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), labelb10);
  gtk_widget_set_size_request (labelb10, 116, -1);
  gtk_label_set_use_markup (GTK_LABEL (labelb10), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entryb10 = gtk_entry_new ();
  gtk_widget_show (entryb10);
  gtk_fixed_put (GTK_FIXED (fixed8), entryb10, 280, 112);
  gtk_widget_set_size_request (entryb10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb10), 8226);

  labelb29 = gtk_label_new ("");
  gtk_widget_show (labelb29);
  gtk_fixed_put (GTK_FIXED (fixed8), labelb29, 360, 248);
  gtk_widget_set_size_request (labelb29, 248, 40);

  buttonb10 = gtk_button_new ();
  gtk_widget_show (buttonb10);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonb10, 232, 176);
  gtk_widget_set_size_request (buttonb10, 160, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonb10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label1262 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label1262);
  gtk_box_pack_start (GTK_BOX (hbox8), label1262, FALSE, FALSE, 0);

  labelb27 = gtk_label_new (_("<span><b>Matricule :</b></span>"));
  gtk_widget_show (labelb27);
  gtk_fixed_put (GTK_FIXED (fixed8), labelb27, 120, 120);
  gtk_widget_set_size_request (labelb27, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelb27), TRUE);

  labelb26 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"blue\">veuillez introduire la matricule d'agricole a supprimer</span>"));
  gtk_widget_show (labelb26);
  gtk_fixed_put (GTK_FIXED (fixed8), labelb26, 96, 32);
  gtk_widget_set_size_request (labelb26, 456, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelb26), TRUE);

  labelb11 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"green\">supprimer</span>"));
  gtk_widget_show (labelb11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), labelb11);
  gtk_widget_set_size_request (labelb11, 116, -1);
  gtk_label_set_use_markup (GTK_LABEL (labelb11), TRUE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox1, 168, 64);
  gtk_widget_set_size_request (combobox1, 192, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("machine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("outil"));

  recherche = gtk_button_new ();
  gtk_widget_show (recherche);
  gtk_fixed_put (GTK_FIXED (fixed12), recherche, 416, 80);
  gtk_widget_set_size_request (recherche, 136, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (recherche), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox14), image17, FALSE, FALSE, 0);

  label1275 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label1275);
  gtk_box_pack_start (GTK_BOX (hbox14), label1275, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed12), scrolledwindow2, 152, 144);
  gtk_widget_set_size_request (scrolledwindow2, 300, 200);

  treeview_rechercher = gtk_tree_view_new ();
  gtk_widget_show (treeview_rechercher);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview_rechercher);
  gtk_widget_set_size_request (treeview_rechercher, 300, 200);

  label1274 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"green\">rechercher</span>"));
  gtk_widget_show (label1274);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label1274);
  gtk_label_set_use_markup (GTK_LABEL (label1274), TRUE);

  g_signal_connect ((gpointer) buttonbackb2, "clicked",
                    G_CALLBACK (on_buttonbackb2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonb7, "clicked",
                    G_CALLBACK (on_buttonb7_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonb13, "clicked",
                    G_CALLBACK (on_buttonb13_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonbackb3, "clicked",
                    G_CALLBACK (on_buttonbackb3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonb9, "clicked",
                    G_CALLBACK (on_buttonb9_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonb10, "clicked",
                    G_CALLBACK (on_buttonb10_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche, "clicked",
                    G_CALLBACK (on_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_rechercher, "row_activated",
                    G_CALLBACK (on_treeview_rechercher_row_activated),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (labelb14), entryb5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (labelb15), entryb6);
  gtk_label_set_mnemonic_widget (GTK_LABEL (labelb16), entry7);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowb3, windowb3, "windowb3");
  GLADE_HOOKUP_OBJECT (windowb3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowb3, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowb3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowb3, entryb3, "entryb3");
  GLADE_HOOKUP_OBJECT (windowb3, entryb4, "entryb4");
  GLADE_HOOKUP_OBJECT (windowb3, entryb5, "entryb5");
  GLADE_HOOKUP_OBJECT (windowb3, entryb6, "entryb6");
  GLADE_HOOKUP_OBJECT (windowb3, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (windowb3, entryb8, "entryb8");
  GLADE_HOOKUP_OBJECT (windowb3, labelb13, "labelb13");
  GLADE_HOOKUP_OBJECT (windowb3, labelb14, "labelb14");
  GLADE_HOOKUP_OBJECT (windowb3, labelb15, "labelb15");
  GLADE_HOOKUP_OBJECT (windowb3, labelb16, "labelb16");
  GLADE_HOOKUP_OBJECT (windowb3, labelb17, "labelb17");
  GLADE_HOOKUP_OBJECT (windowb3, labelb12, "labelb12");
  GLADE_HOOKUP_OBJECT (windowb3, buttonbackb2, "buttonbackb2");
  GLADE_HOOKUP_OBJECT (windowb3, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowb3, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowb3, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowb3, label1256, "label1256");
  GLADE_HOOKUP_OBJECT (windowb3, buttonb7, "buttonb7");
  GLADE_HOOKUP_OBJECT (windowb3, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowb3, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowb3, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowb3, label1255, "label1255");
  GLADE_HOOKUP_OBJECT (windowb3, label100, "label100");
  GLADE_HOOKUP_OBJECT (windowb3, labelb8, "labelb8");
  GLADE_HOOKUP_OBJECT (windowb3, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowb3, buttonb13, "buttonb13");
  GLADE_HOOKUP_OBJECT (windowb3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowb3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowb3, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowb3, label1260, "label1260");
  GLADE_HOOKUP_OBJECT (windowb3, buttonbackb3, "buttonbackb3");
  GLADE_HOOKUP_OBJECT (windowb3, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowb3, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowb3, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowb3, label1261, "label1261");
  GLADE_HOOKUP_OBJECT (windowb3, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowb3, treeviewb1, "treeviewb1");
  GLADE_HOOKUP_OBJECT (windowb3, labelb9, "labelb9");
  GLADE_HOOKUP_OBJECT (windowb3, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowb3, entryb9, "entryb9");
  GLADE_HOOKUP_OBJECT (windowb3, buttonb9, "buttonb9");
  GLADE_HOOKUP_OBJECT (windowb3, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowb3, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowb3, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowb3, label1263, "label1263");
  GLADE_HOOKUP_OBJECT (windowb3, labelb25, "labelb25");
  GLADE_HOOKUP_OBJECT (windowb3, labelb24, "labelb24");
  GLADE_HOOKUP_OBJECT (windowb3, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowb3, labelb10, "labelb10");
  GLADE_HOOKUP_OBJECT (windowb3, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowb3, entryb10, "entryb10");
  GLADE_HOOKUP_OBJECT (windowb3, labelb29, "labelb29");
  GLADE_HOOKUP_OBJECT (windowb3, buttonb10, "buttonb10");
  GLADE_HOOKUP_OBJECT (windowb3, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowb3, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowb3, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowb3, label1262, "label1262");
  GLADE_HOOKUP_OBJECT (windowb3, labelb27, "labelb27");
  GLADE_HOOKUP_OBJECT (windowb3, labelb26, "labelb26");
  GLADE_HOOKUP_OBJECT (windowb3, labelb11, "labelb11");
  GLADE_HOOKUP_OBJECT (windowb3, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowb3, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (windowb3, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (windowb3, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowb3, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowb3, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowb3, label1275, "label1275");
  GLADE_HOOKUP_OBJECT (windowb3, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (windowb3, treeview_rechercher, "treeview_rechercher");
  GLADE_HOOKUP_OBJECT (windowb3, label1274, "label1274");

  return windowb3;
}

GtkWidget*
create_windowb6 (void)
{
  GtkWidget *windowb6;
  GtkWidget *fixed11;
  GtkWidget *entryb11;
  GtkWidget *entryb12;
  GtkWidget *entryb13;
  GtkWidget *entryb14;
  GtkWidget *entryb15;
  GtkWidget *entryb16;
  GtkWidget *label1273;
  GtkWidget *label1271;
  GtkWidget *label1272;
  GtkWidget *label1270;
  GtkWidget *label1269;
  GtkWidget *label1268;
  GtkWidget *buttonb14;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label1267;
  GtkWidget *buttonb963;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label1266;
  GtkWidget *labelb30;
  GtkWidget *label2;

  windowb6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowb6), _("modifier"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (windowb6), fixed11);

  entryb11 = gtk_entry_new ();
  gtk_widget_show (entryb11);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb11, 248, 80);
  gtk_widget_set_size_request (entryb11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb11), 8226);

  entryb12 = gtk_entry_new ();
  gtk_widget_show (entryb12);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb12, 248, 120);
  gtk_widget_set_size_request (entryb12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb12), 8226);

  entryb13 = gtk_entry_new ();
  gtk_widget_show (entryb13);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb13, 248, 160);
  gtk_widget_set_size_request (entryb13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb13), 8226);

  entryb14 = gtk_entry_new ();
  gtk_widget_show (entryb14);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb14, 248, 200);
  gtk_widget_set_size_request (entryb14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb14), 8226);

  entryb15 = gtk_entry_new ();
  gtk_widget_show (entryb15);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb15, 248, 240);
  gtk_widget_set_size_request (entryb15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb15), 8226);

  entryb16 = gtk_entry_new ();
  gtk_widget_show (entryb16);
  gtk_fixed_put (GTK_FIXED (fixed11), entryb16, 248, 288);
  gtk_widget_set_size_request (entryb16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryb16), 8226);

  label1273 = gtk_label_new_with_mnemonic (_("<span><b>Ann\303\251e \303\240 modifier :</b></span>"));
  gtk_widget_show (label1273);
  gtk_fixed_put (GTK_FIXED (fixed11), label1273, 80, 296);
  gtk_widget_set_size_request (label1273, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (label1273), TRUE);

  label1271 = gtk_label_new_with_mnemonic (_("<span><b>Num d'identifiant \303\240 modifier :</b></span>"));
  gtk_widget_show (label1271);
  gtk_fixed_put (GTK_FIXED (fixed11), label1271, 16, 208);
  gtk_widget_set_size_request (label1271, 232, 16);
  gtk_label_set_use_markup (GTK_LABEL (label1271), TRUE);

  label1272 = gtk_label_new_with_mnemonic (_("<span><b>Puissance \303\240 modifier :</b></span>"));
  gtk_widget_show (label1272);
  gtk_fixed_put (GTK_FIXED (fixed11), label1272, 72, 248);
  gtk_widget_set_size_request (label1272, 168, 16);
  gtk_label_set_use_markup (GTK_LABEL (label1272), TRUE);

  label1270 = gtk_label_new_with_mnemonic (_("<span><b>Matricule \303\240 modifier :</b></span>"));
  gtk_widget_show (label1270);
  gtk_fixed_put (GTK_FIXED (fixed11), label1270, 80, 168);
  gtk_widget_set_size_request (label1270, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label1270), TRUE);

  label1269 = gtk_label_new_with_mnemonic (_("<span><b>Marque \303\240 modifier :</b></span>"));
  gtk_widget_show (label1269);
  gtk_fixed_put (GTK_FIXED (fixed11), label1269, 64, 128);
  gtk_widget_set_size_request (label1269, 176, 16);
  gtk_label_set_use_markup (GTK_LABEL (label1269), TRUE);

  label1268 = gtk_label_new_with_mnemonic (_("<span><b>Type \303\240 modifier :</b></span>"));
  gtk_widget_show (label1268);
  gtk_fixed_put (GTK_FIXED (fixed11), label1268, 96, 80);
  gtk_widget_set_size_request (label1268, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label1268), TRUE);

  buttonb14 = gtk_button_new ();
  gtk_widget_show (buttonb14);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonb14, 456, 96);
  gtk_widget_set_size_request (buttonb14, 120, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonb14), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label1267 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label1267);
  gtk_box_pack_start (GTK_BOX (hbox13), label1267, FALSE, FALSE, 0);

  buttonb963 = gtk_button_new ();
  gtk_widget_show (buttonb963);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonb963, 528, 192);
  gtk_widget_set_size_request (buttonb963, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonb963), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label1266 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label1266);
  gtk_box_pack_start (GTK_BOX (hbox12), label1266, FALSE, FALSE, 0);

  labelb30 = gtk_label_new (_("\n<span font_desc=\"Purisa\"foreground=\"green\"> Modifier un agricole</span>"));
  gtk_widget_show (labelb30);
  gtk_fixed_put (GTK_FIXED (fixed11), labelb30, 192, 16);
  gtk_widget_set_size_request (labelb30, 312, 48);
  gtk_label_set_use_markup (GTK_LABEL (labelb30), TRUE);
  gtk_misc_set_alignment (GTK_MISC (labelb30), 0.57, 0.5);

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed11), label2, 376, 144);
  gtk_widget_set_size_request (label2, 256, 40);

  g_signal_connect ((gpointer) buttonb14, "clicked",
                    G_CALLBACK (on_buttonb14_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonb963, "clicked",
                    G_CALLBACK (on_buttonb963_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label1268), entryb11);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowb6, windowb6, "windowb6");
  GLADE_HOOKUP_OBJECT (windowb6, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (windowb6, entryb11, "entryb11");
  GLADE_HOOKUP_OBJECT (windowb6, entryb12, "entryb12");
  GLADE_HOOKUP_OBJECT (windowb6, entryb13, "entryb13");
  GLADE_HOOKUP_OBJECT (windowb6, entryb14, "entryb14");
  GLADE_HOOKUP_OBJECT (windowb6, entryb15, "entryb15");
  GLADE_HOOKUP_OBJECT (windowb6, entryb16, "entryb16");
  GLADE_HOOKUP_OBJECT (windowb6, label1273, "label1273");
  GLADE_HOOKUP_OBJECT (windowb6, label1271, "label1271");
  GLADE_HOOKUP_OBJECT (windowb6, label1272, "label1272");
  GLADE_HOOKUP_OBJECT (windowb6, label1270, "label1270");
  GLADE_HOOKUP_OBJECT (windowb6, label1269, "label1269");
  GLADE_HOOKUP_OBJECT (windowb6, label1268, "label1268");
  GLADE_HOOKUP_OBJECT (windowb6, buttonb14, "buttonb14");
  GLADE_HOOKUP_OBJECT (windowb6, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowb6, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowb6, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowb6, label1267, "label1267");
  GLADE_HOOKUP_OBJECT (windowb6, buttonb963, "buttonb963");
  GLADE_HOOKUP_OBJECT (windowb6, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowb6, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowb6, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowb6, label1266, "label1266");
  GLADE_HOOKUP_OBJECT (windowb6, labelb30, "labelb30");
  GLADE_HOOKUP_OBJECT (windowb6, label2, "label2");

  return windowb6;
}

